---
- name: Playbook para sacar parches windows y uptime linux
  hosts: windows
  become: false
  gather_facts: false
  tasks:
  - name: Crea directorio de temp windows
    ansible.windows.win_file:
      path: c:/users/ansible/desktop/temp/
      state: directory